# Generated by Django 3.1.4 on 2020-12-18 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=250)),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('oth', 'Others'), ('wor', 'Work/Career'), ('fnc', 'Finance'), ('soc', 'Social'), ('fam', 'Family'), ('int', 'Intellectual'), ('fit', 'Health/Fitness'), ('spi', 'Spiritual'), ('edu', 'Education'), ('adv', 'Travel/Adventure'), ('hob', 'Hobbies')], max_length=43)),
                ('restricted', models.BooleanField(default=False)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('goaldate', models.DateField(blank=True, null=True, verbose_name='set goal date')),
                ('completiondate', models.DateField(blank=True, null=True, verbose_name='completion date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=250)),
                ('restricted', models.BooleanField(default=False)),
                ('goal', models.ManyToManyField(to='main_app.Goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
