# Generated by Django 3.1.4 on 2020-12-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='GoalList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('decription', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=250)),
                ('restricted', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('goaldate', models.DateField(verbose_name='set goal date')),
                ('completiondate', models.DateField(verbose_name='completion date')),
                ('category', models.ManyToManyField(to='main_app.Category')),
            ],
        ),
    ]
