# Generated by Django 3.1.4 on 2020-12-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.Category'),
        ),
    ]
