# Generated by Django 3.1.4 on 2020-12-21 23:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('oth', 'Others'), ('wor', 'Work/Career'), ('fnc', 'Finance'), ('soc', 'Social'), ('fam', 'Family'), ('int', 'Intellectual'), ('fit', 'Health/Fitness'), ('spi', 'Spiritual'), ('edu', 'Education'), ('adv', 'Travel/Adventure'), ('hob', 'Hobbies')], default='oth', max_length=43),
        ),
    ]
