# Generated by Django 3.1.4 on 2020-12-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goallist',
            name='category',
            field=models.ManyToManyField(to='main_app.Category'),
        ),
    ]
