# Generated by Django 3.1.4 on 2020-12-17 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='completiondate',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goaldate',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='restricted',
        ),
    ]
