# Generated by Django 3.1.4 on 2020-12-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='category',
        ),
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('Others', 'Others'), ('Work/Career', 'Work/Career'), ('Finance', 'Finance'), ('Social', 'Social'), ('Family', 'Family'), ('Intellectual', 'Intellectual'), ('Health/Fitness', 'Health/Fitness'), ('Spiritual', 'Spiritual'), ('Education', 'Education'), ('Travel/Adventure', 'Travel/Adventure'), ('Hobbies', 'Hobbies')], default='Others', max_length=25),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
