# Generated by Django 3.1.4 on 2020-12-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_goallist_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goallist',
            old_name='decription',
            new_name='description',
        ),
    ]
