# Generated by Django 3.1.4 on 2020-12-16 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_goallist_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goallist',
            old_name='decription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='goallist',
            name='goal',
            field=models.ManyToManyField(to='main_app.Goal'),
        ),
        migrations.AddField(
            model_name='goallist',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goallist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
