# Generated by Django 3.1.4 on 2020-12-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201217_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.ManyToManyField(blank=True, to='main_app.Category'),
        ),
        migrations.AlterField(
            model_name='goallist',
            name='category',
            field=models.ManyToManyField(blank=True, to='main_app.Category'),
        ),
    ]
