# Generated by Django 3.1.2 on 2020-12-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201221_2108'),
        ('main_app', '0002_auto_20201221_2302'),
    ]

    operations = [
    ]
